// build.zig - generated by fano-poly for project "demo".
// Reuses the FANO poly runtime at FANO_ZIG_ROOT (or the baked path).
const std = @import("std");

pub fn build(b: *std.Build) void {
    const root = std.process.getEnvVarOwned(b.allocator, "FANO_ZIG_ROOT") catch null;
    const fano: []const u8 = if (root) |r| r else "/home/projects/Q128.128/zig";
    defer if (root) |r| b.allocator.free(r);
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    const q128_mod = b.createModule(.{ .root_source_file = .{ .cwd_relative = b.fmt("{s}/q128_128.zig", .{fano}) }, .target = target, .optimize = optimize });
    const poly_mod = b.createModule(.{ .root_source_file = .{ .cwd_relative = b.fmt("{s}/poly/poly.zig", .{fano}) }, .target = target, .optimize = optimize });
    poly_mod.addImport("q128_128", q128_mod);
    poly_mod.addIncludePath(.{ .cwd_relative = b.fmt("{s}/poly/vendor", .{fano}) });
    poly_mod.addIncludePath(.{ .cwd_relative = b.fmt("{s}/poly/c_guest", .{fano}) });
    poly_mod.addCSourceFiles(.{
        .root = .{ .cwd_relative = b.fmt("{s}/poly/vendor", .{fano}) },
        .files = &.{ "quickjs.c", "libregexp.c", "libunicode.c", "libbf.c", "cutils.c" },
        .flags = &.{ "-D_GNU_SOURCE", "-DCONFIG_VERSION=\"2024-01-13\"", "-O2", "-fno-sanitize=undefined" },
    });
    poly_mod.addCSourceFile(.{ .file = .{ .cwd_relative = b.fmt("{s}/poly/c_guest/guest.c", .{fano}) }, .flags = &.{ "-O2", "-fno-sanitize=undefined" } });
    poly_mod.link_libc = true;
    if (detectPython(b)) |py| {
        poly_mod.addSystemIncludePath(.{ .cwd_relative = py.include });
        poly_mod.addLibraryPath(.{ .cwd_relative = py.libdir });
        poly_mod.linkSystemLibrary(b.fmt("python{s}", .{py.ldversion}), .{});
    }

    const exe = b.addExecutable(.{ .name = "demo", .root_source_file = b.path("main.zig"), .target = target, .optimize = optimize });
    exe.root_module.addImport("poly", poly_mod);
    b.installArtifact(exe);
    const run = b.addRunArtifact(exe);
    if (b.args) |args| run.addArgs(args);
    b.step("run", "Run the fano-poly project").dependOn(&run.step);
}

const PyInfo = struct { include: []const u8, libdir: []const u8, ldversion: []const u8 };
fn detectPython(b: *std.Build) ?PyInfo {
    const a = b.allocator;
    const home = std.process.getEnvVarOwned(a, "HOME") catch return null;
    const pyenv_inc = std.fmt.allocPrint(a, "{s}/.pyenv/versions/3.11.9/include/python3.11", .{home}) catch return null;
    if (std.fs.accessAbsolute(pyenv_inc, .{})) |_| {
        const pyenv_lib = std.fmt.allocPrint(a, "{s}/.pyenv/versions/3.11.9/lib", .{home}) catch return null;
        return .{ .include = pyenv_inc, .libdir = pyenv_lib, .ldversion = "3.11" };
    } else |_| {}
    if (std.fs.accessAbsolute("/usr/include/python3.11", .{})) |_| {
        return .{ .include = "/usr/include/python3.11", .libdir = "/usr/lib", .ldversion = "3.11" };
    } else |_| {}
    return null;
}
