// main.zig - generated by fano-poly for project "demo".
const std = @import("std");
const poly = @import("poly");

// The QuickJS engine is module-level so the generated js_* bindings
// can reach it without capturing a local from main.
var g_engine: poly.QuickJS = undefined;
// py fn add (line 5)
fn py_add(a: poly.I256, b: poly.I256) poly.PolyError!poly.I256 {
    var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
    defer arena.deinit();
    const al = arena.allocator();
    const d_a = try poly.i256ToDecimal(al, a);
    const d_b = try poly.i256ToDecimal(al, b);
    const expr = try std.fmt.allocPrint(al, "add({s}, {s})", .{d_a, d_b});
    return poly.Python.evalI256(expr);
}

// js fn mulq (line 9)
fn js_mulq(a: poly.I256, b: poly.I256) poly.PolyError!poly.I256 {
    var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
    defer arena.deinit();
    const al = arena.allocator();
    const d_a = try poly.i256ToDecimal(al, a);
    const d_b = try poly.i256ToDecimal(al, b);
    const expr = try std.fmt.allocPrint(al, "mulq(BigInt(\"{s}\"), BigInt(\"{s}\"))", .{d_a, d_b});
    return g_engine.evalI256(expr);
}

pub fn main() !void {
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    const alloc = gpa.allocator();
    try poly.Python.init();
    g_engine = try poly.QuickJS.init();
    defer g_engine.deinit();
    // Define the Python guest functions by execing polygen.py into
    // __main__ (embedded CPython's sys.path does not include the
    // CWD, so a plain `import polygen` is unreliable).
    const py_src = try std.fs.cwd().readFileAlloc(alloc, "polygen.py", 1 << 20);
    defer alloc.free(py_src);
    try poly.Python.run(py_src);
    // Load the JS guest module by evaluating polygen.js once.
    const js_src = try std.fs.cwd().readFileAlloc(alloc, "polygen.js", 1 << 20);
    defer alloc.free(js_src);
    _ = try g_engine.eval(alloc, js_src);
    // zig fn main (line 13)
    // 1.5 and 2.5 in Q128.128 fixed point.
    const a = poly.i256FromQ128(.{ .hi = 1, .lo = @as(u128, 1) << 127 });
    const b = poly.i256FromQ128(.{ .hi = 2, .lo = @as(u128, 1) << 127 });
    const sum = try py_add(a, b);    // 1.5 + 2.5 = 4.0
    const prod = try js_mulq(a, b);  // 1.5 * 2.5 = 3.75 (fixed-point)
    const sum_q = poly.i256ToQ128(sum);
    const prod_q = poly.i256ToQ128(prod);
    // Integer part in hi; fractional part scaled to milli (lo * 1000 >> 128).
    std.debug.print("py add  1.5 + 2.5 = {d}.{d}\n", .{ sum_q.hi, @as(u64, @intCast((@as(u256, sum_q.lo) * 1000) >> 128)) });
    std.debug.print("js mul  1.5 * 2.5 = {d}.{d}\n", .{ prod_q.hi, @as(u64, @intCast((@as(u256, prod_q.lo) * 1000) >> 128)) });
}
